[package]
name = "lights"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#tokio = { version = "1.32", features = ["full"] }
gpio = "0.4.1"
unbothered-gpio = "0.1.0"
rppal = "0.15.0"
